workflows:
  build:
    name: Build Workflow
    environment:
      flutter: stable
    scripts:
    
      - name: Prepare CocoaPods
        script: |
          sudo gem install cocoapods
          cd ios
          pod repo update
          rm Podfile.lock
          rm -rf Pods
          pod install
          cd ..

      - name: Update Flutter and Plugins
        script: |
          flutter upgrade
          flutter pub get

      - name: Fix Xcode Build Error
        script: |
          # Check if the file exists
          if [ ! -e '/Users/builder/clone/build/ios/Debug-iphoneos/OneSignalNotificationServiceExtension.appex/OneSignalNotificationServiceExtension' ]; then
            echo "File not found. Generating or copying the missing file..."
            
            # Replace the following line with the actual command to generate or copy the file
            # For example, if you need to generate the file, you can use a build command.
            # If you need to copy the file from a specific location, use the 'cp' command.
            
            # Example (replace with your actual command):
            # Generate the file (replace with your actual command):
            # ./generate_missing_file.sh
            
            # OR
            
            # Copy the file (replace with your actual command):
            cp '/Users/builder/clone/build/ios/Debug-iphoneos/OneSignalNotificationServiceExtension.appex/OneSignalNotificationServiceExtension'
            
          else
            echo "File found. No action needed."
          fi
    - name: Pre-Build
      script:
        - |
          # Copy the OneSignalNotificationServiceExtension.appex directory to the expected location
          # Replace 'SOURCE_PATH' and 'DESTINATION_PATH' with the actual paths
          
          SOURCE_PATH="/Users/builder/clone/build/ios/Debug-iphoneos/OneSignalNotificationServiceExtension.appex"
          DESTINATION_PATH="/Runner/OneSignalNotificationServiceExtension.appex"

          # Check if the source directory exists
          if [ -d "$SOURCE_PATH" ]; then
            # Create the destination folder if it doesn't exist
            mkdir -p "$(dirname "$DESTINATION_PATH")"
            # Copy the source directory to the destination
            cp -R "$SOURCE_PATH" "$DESTINATION_PATH"
          else
            echo "Error: Source directory not found at $SOURCE_PATH"
            exit 1
          fi

      - name: Build iOS
        script: |
          flutter build ios --debug --no-codesign

      # Add additional steps for deployment, if needed

      
